name: Build and Publish ESP32 Firmware

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Compile Binaries
      run: |
        # Run the Docker container to build the project
        cd ESP-Miner-NerdQAxePlus && \
        chown 1000:1000 . -R && \
        docker run --rm -v $PWD:/home/builder/project \
        shufps/esp-idf-builder:0.0.1 idf.py build

    - name: Merge Binaries
      run: |
        docker run --rm -v $PWD:/home/builder/project \
        shufps/esp-idf-builder:0.0.1 esptool.py --chip esp32s3 merge_bin --flash_mode dio --flash_size 16MB --flash_freq 80m \
        0x0 build/bootloader/bootloader.bin \
        0x8000 build/partition_table/partition-table.bin \
        0x10000 build/esp-miner.bin \
        0x410000 build/www.bin \
        0xf10000 build/ota_data_initial.bin \
        -o esp-miner-factory-nerdqaxe+.bin

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: nerdqaxe-firmware
        path: esp-miner-factory-nerdqaxe+.bin

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: nerdqaxe-firmware

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: myorg/esp32-firmware
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=match,pattern=v(\d+.\d+),suffix=-alpha,group=1,enable=${{ contains(github.ref, '-alpha') }}
          type=match,pattern=v(\d+.\d+),suffix=-beta,group=1,enable=${{ contains(github.ref, '-beta') }}
          type=match,pattern=v(\d+.\d+),suffix=-rc,group=1,enable=${{ contains(github.ref, '-rc') }}

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: 'Firmware Release'
        tag: ${{ steps.meta.outputs.version }}
        files: esp-miner-factory-nerdqaxe+.bin
        body: |
          Automatically generated firmware release.

