name: Build and Publish ESP32 Firmware

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Compile Binaries
      run: |
        # Run the Docker container to build the project
        cd /home/runner/work/ESP-Miner-NerdQAxePlus/ESP-Miner-NerdQAxePlus && \
        docker run --rm --user root -v $PWD:/home/builder/project \
        shufps/esp-idf-builder:0.0.1 idf.py build

    - name: Merge Binaries
      run: |
        docker run --rm --user root -v $PWD:/home/builder/project \
        shufps/esp-idf-builder:0.0.1 esptool.py --chip esp32s3 merge_bin --flash_mode dio --flash_size 16MB --flash_freq 80m \
        0x0 build/bootloader/bootloader.bin \
        0x8000 build/partition_table/partition-table.bin \
        0x10000 build/esp-miner.bin \
        0x410000 build/www.bin \
        0xf10000 build/ota_data_initial.bin \
        -o esp-miner-factory-nerdqaxe+.bin

    - name: Generate Version Tag
      id: version_tag
      run: |
        git fetch --tags  # Ensure all tags are fetched

        if git describe --tags --abbrev=0 >/dev/null 2>&1; then
          version=$(git describe --tags --abbrev=0)
        else
          version="v0.0.0"
        fi
        echo "VERSION_TAG=${version}" >> $GITHUB_ENV

    - name: Rename Binary with Version
      run: |
        mv esp-miner-factory-nerdqaxe+.bin esp-miner-factory-nerdqaxe-${{ env.VERSION_TAG }}.bin

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: nerdqaxe-firmware
        path: esp-miner-factory-nerdqaxe-${{ env.VERSION_TAG }}.bin
        
  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: nerdqaxe-firmware

    - name: Generate Changelog
      id: changelog
      run: |
        git fetch --tags  # Ensure all tags are fetched

        if git describe --tags --abbrev=0 >/dev/null 2>&1; then
          version=$(git describe --tags --abbrev=0)
        else
          version="v0.0.0"
        fi
        echo "VERSION_TAG=${version}" >> $GITHUB_ENV        
        
        # Generate a changelog from the last tag to the current commit
        changelog=$(git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:'* %s' --no-merges)
        echo "CHANGELOG=$changelog" >> $GITHUB_ENV

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: 'Firmware Release ${{ env.VERSION_TAG }}'
        tag: ${{ env.VERSION_TAG }}
        artifacts: esp-miner-factory-nerdqaxe-${{ env.VERSION_TAG }}.bin
        body: |
          ## Changelog
          ${{ env.CHANGELOG }}
