name: Build and Release ESP32 Firmware

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get Version Tag
      id: version_tag
      run: |
        git fetch --tags  # Ensure all tags are fetched

        if git describe --tags --abbrev=0 >/dev/null 2>&1; then
          version=$(git describe --tags --abbrev=0)
        else
          version="v0.0.0"
        fi
        echo "VERSION_TAG=${version}" >> $GITHUB_ENV
        echo "VERSION_TAG=${version}"
        
    - name: Compile Binaries
      run: |
        # Run the Docker container to build the project
        cd /home/runner/work/ESP-Miner-NerdQAxePlus/ESP-Miner-NerdQAxePlus && \
        docker run --rm --user root -v $PWD:/home/builder/project \
        shufps/esp-idf-builder:0.0.1 idf.py build

    - name: Merge Binaries
      run: |
        docker run --rm --user root -v $PWD:/home/builder/project \
        shufps/esp-idf-builder:0.0.1 esptool.py --chip esp32s3 merge_bin --flash_mode dio --flash_size 16MB --flash_freq 80m \
        0x0 build/bootloader/bootloader.bin \
        0x8000 build/partition_table/partition-table.bin \
        0x10000 build/esp-miner.bin \
        0x410000 build/www.bin \
        0xf10000 build/ota_data_initial.bin \
        -o esp-miner-factory-nerdqaxe-${{ env.VERSION_TAG }}.bin

    - name: Upload to Existing Release
      uses: softprops/action-gh-release@v1
      with:
        files: esp-miner-factory-nerdqaxe-${{ env.VERSION_TAG }}.bin, ./build/esp-miner.bin, ./build/www.bin
        tag_name: ${{ env.VERSION_TAG }}
        token: ${{ secrets.GITHUB_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
